export const styles = {
  wrapper: { maxWidth: 600, margin: "0 auto", padding: "40px 24px 60px", minHeight: "auto", fontFamily: "'Nunito', sans-serif", color: "#1A2E1A", background: "#FAFDF9", borderRadius: 12 },
  topBar: { display: "flex", alignItems: "center", justifyContent: "space-between", padding: "8px 0 24px" },
  logo: { fontSize: 22, fontWeight: 800, letterSpacing: -0.3 },
  stepCount: { fontSize: 13, fontWeight: 600, color: "#3D9141", background: "#EAF7EB", padding: "4px 12px", borderRadius: 20 },
  progressTrack: { width: "100%", height: 6, background: "#E2EADE", borderRadius: 3, marginBottom: 32, overflow: "hidden" },
  progressFill: { height: "100%", background: "#4BAF4F", borderRadius: 3, transition: "width 0.4s cubic-bezier(0.4,0,0.2,1)" },
  page: { display: "flex", flexDirection: "column", flex: 1, animation: "fadeIn 0.25s ease" },
  pageTitle: { fontSize: 26, fontWeight: 800, marginBottom: 6 },
  pageDesc: { fontSize: 15, color: "#4A6A4A", marginBottom: 28 },
  callout: { background: "#F4FBF4", border: "1px solid #E2EADE", borderRadius: 10, padding: "14px 16px", fontSize: 14, color: "#4A6A4A", lineHeight: 1.6 },
  input: { width: "100%", padding: "12px 14px", border: "2px solid #E2EADE", borderRadius: 10, fontFamily: "'Nunito', sans-serif", fontSize: 15, color: "#1A2E1A", background: "#fff", outline: "none", boxSizing: "border-box" },
  textarea: { width: "100%", padding: "12px 14px", border: "2px solid #E2EADE", borderRadius: 10, fontFamily: "'Nunito', sans-serif", fontSize: 15, color: "#1A2E1A", background: "#fff", outline: "none", resize: "vertical", minHeight: 90, boxSizing: "border-box" },
  taskCard: { background: "#EAF7EB", borderRadius: 10, padding: 16, marginBottom: 20 },
  taskNum: { fontSize: 11, fontWeight: 800, textTransform: "uppercase", letterSpacing: 1, color: "#4BAF4F", marginBottom: 4 },
  rBtn: { flex: 1, height: 42, border: "2px solid #E2EADE", borderRadius: 10, background: "#fff", fontFamily: "'Nunito', sans-serif", fontSize: 15, fontWeight: 700, color: "#7A9A7A", cursor: "pointer", transition: "all 0.15s" },
  rBtnSel: { background: "#4BAF4F", borderColor: "#4BAF4F", color: "#fff" },
  npsBtn: { flex: 1, height: 44, border: "2px solid #E2EADE", borderRadius: 10, background: "#fff", fontFamily: "'Nunito', sans-serif", fontSize: 14, fontWeight: 700, color: "#7A9A7A", cursor: "pointer", transition: "all 0.15s" },
  npsBtnSel: { background: "#4BAF4F", borderColor: "#4BAF4F", color: "#fff" },
  ynBtn: { padding: "8px 20px", border: "2px solid #E2EADE", borderRadius: 24, background: "#fff", fontFamily: "'Nunito', sans-serif", fontSize: 13, fontWeight: 700, color: "#4A6A4A", cursor: "pointer", transition: "all 0.15s" },
  ynBtnSel: { background: "#4BAF4F", borderColor: "#4BAF4F", color: "#fff" },
  entry: { background: "#F4FBF4", borderRadius: 10, padding: 16, marginBottom: 12 },
  entryLabel: { fontSize: 12, fontWeight: 800, textTransform: "uppercase", letterSpacing: 0.8, color: "#4BAF4F", marginBottom: 10 },
  navBar: { display: "flex", gap: 12, marginTop: "auto", padding: "24px 0 16px" },
  btnBack: { padding: "14px 28px", borderRadius: 10, fontFamily: "'Nunito', sans-serif", fontSize: 15, fontWeight: 700, cursor: "pointer", border: "none", background: "#EAF7EB", color: "#3D9141" },
  btnNext: { flex: 1, padding: "14px 28px", borderRadius: 10, fontFamily: "'Nunito', sans-serif", fontSize: 15, fontWeight: 700, cursor: "pointer", border: "none", background: "#4BAF4F", color: "#fff" },
  success: { textAlign: "center", padding: "100px 20px", display: "flex", flexDirection: "column", alignItems: "center" },
  successCheck: { width: 72, height: 72, background: "#EAF7EB", borderRadius: "50%", display: "flex", alignItems: "center", justifyContent: "center", marginBottom: 24 },
};
